services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data/data
    environment:
      - 'REDIS_PASSWORD=password'
    ports:
      - 6379:6379
volumes:
  redis_data: